# Generated by Django 4.0.6 on 2022-07-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nave',
            fields=[
                ('IdNave', models.AutoField(primary_key=True, serialize=False)),
                ('NombreNave', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tripulante',
            fields=[
                ('IdTripulante', models.AutoField(primary_key=True, serialize=False)),
                ('NombreTripulante', models.CharField(max_length=100)),
                ('Nave', models.CharField(max_length=100)),
                ('FechaDeIncorporacion', models.CharField()),
                ('FotoFilename', models.CharField(max_length=100)),
            ],
        ),
    ]
