# Generated by Django 4.1.3 on 2022-11-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nave',
            fields=[
                ('IdNave', models.AutoField(primary_key=True, serialize=False)),
                ('NombreNave', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tripulante',
            fields=[
                ('IdTripulante', models.AutoField(primary_key=True, serialize=False)),
                ('NombreTripulante', models.CharField(max_length=100)),
                ('NaveTripulante', models.CharField(default='SOME STRING', max_length=100)),
            ],
        ),
    ]
