# Generated by Django 4.0.6 on 2022-07-09 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpleadoApp', '0002_alter_tripulante_fechadeincorporacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripulante',
            name='FechaDeIncorporacion',
        ),
    ]
