# Generated by Django 4.0.6 on 2022-07-09 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpleadoApp', '0003_remove_tripulante_fechadeincorporacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripulante',
            name='FotoFilename',
        ),
        migrations.RemoveField(
            model_name='tripulante',
            name='Nave',
        ),
    ]
